
name: flutter_firebase_codespaces
description: A new Flutter project with Firebase support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 以下のパッケージは、flutter と同じインデントレベルに配置
  firebase_core: ^4.0.0
  # 他のFirebaseパッケージは必要に応じて追加してください

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 以下のパッケージは、flutter と同じインデントレベルに配置
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
